# Project: Bresenham
# Makefile created by Dev-C++ 6.7.5

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Bresenham.o
LINKOBJ  = Bresenham.o
LIBS     = -L"D:/Dev-Cpp/MinGW64/TDM-GCC-32/lib/gcc/mingw32/10.3.0/" -L"D:/Dev-Cpp/MinGW64/TDM-GCC-32/lib/gcc/" -L"D:/Dev-Cpp/MinGW64/TDM-GCC-32/mingw32/lib/" -L"D:/Dev-Cpp/MinGW64/TDM-GCC-32/lib/" -L"D:/Dev-Cpp/MinGW64/TDM-GCC-32/lib" -L"D:/Dev-Cpp/MinGW64/TDM-GCC-32/mingw32/lib" -s -lbgi -lgdi32 -luser32 -static
INCS     = -I"D:/Dev-Cpp/MinGW64/TDM-GCC-32/lib/gcc/mingw32/10.3.0/include" -I"D:/Dev-Cpp/MinGW64/TDM-GCC-32/include" -I"D:/Dev-Cpp/MinGW64/TDM-GCC-32/lib/gcc/mingw32/10.3.0/include-fixed"
CXXINCS  = -I"D:/Dev-Cpp/MinGW64/TDM-GCC-32/lib/gcc/mingw32/10.3.0/include/c++" -I"D:/Dev-Cpp/MinGW64/TDM-GCC-32/lib/gcc/mingw32/10.3.0/include/c++/mingw32" -I"D:/Dev-Cpp/MinGW64/TDM-GCC-32/lib/gcc/mingw32/10.3.0/include/c++/backward" -I"D:/Dev-Cpp/MinGW64/TDM-GCC-32/lib/gcc/mingw32/10.3.0/include" -I"D:/Dev-Cpp/MinGW64/TDM-GCC-32/include" -I"D:/Dev-Cpp/MinGW64/TDM-GCC-32/lib/gcc/mingw32/10.3.0/include-fixed"
BIN      = Bresenham.exe
CXXFLAGS = $(CXXINCS) -O2
ENCODINGS = -finput-charset=utf-8 -fexec-charset=windows-1252
CFLAGS   = $(INCS) -O2
RM       = del /q /f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "$(BIN)" $(LIBS)

Bresenham.o: Bresenham.cpp
	$(CPP) -c Bresenham.cpp -o Bresenham.o $(CXXFLAGS) 
